# Generated by Django 6.0.3 on 2026-03-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('intent', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('page_number', models.IntegerField(null=True)),
                ('bounding_boxes', models.JSONField(default=list)),
                ('page_width', models.FloatField(null=True)),
                ('page_height', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('is_open_access', models.BooleanField(default=False)),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='documents.citation')),
            ],
        ),
    ]
