# Generated by Django 6.0.3 on 2026-03-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_citation_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='influential_citations',
            field=models.IntegerField(default=0),
        ),
    ]
