# Generated by Django 6.0.3 on 2026-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_recommendation_influential_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='citation_style',
            field=models.CharField(default='apa', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='manuscript_content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
