# Generated by Django 6.0.3 on 2026-05-19 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_manuscript_inserted_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertedCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.TextField(blank=True)),
                ('formatted_intext', models.TextField()),
                ('csl_item', models.JSONField(default=dict)),
                ('anchor_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citation_gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insertions', to='documents.citation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserted_citations', to='documents.document')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insertions', to='documents.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
