# Generated by Django 6.0.3 on 2026-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_year_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertedcitation',
            name='pdf_position',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
